# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
<<<<<<< HEAD
title: Yonney's Blog
subtitle: 越努力才会越幸运 	
description: 
author: MiKi Yonney
email: mikiyonney@gmail.com
language: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mikiyonney.github.io/
=======
title: Hexo
subtitle:
description:
author: John Doe
email:
language:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
<<<<<<< HEAD
archive: 1
category: 1
tag: 1
=======
archive: 2
category: 2
tag: 2
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

<<<<<<< HEAD
# Pagination 
=======
# Pagination
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
<<<<<<< HEAD
disqus_shortname: MiKiYonney
=======
disqus_shortname:
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
<<<<<<< HEAD
theme: hexo-theme-tyrant
=======
theme: landscape
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  type: github
  repository: git@github.com:MiKiYonney/mikiyonney.github.io.git
<<<<<<< HEAD
  branch: master
=======
  branch: master
>>>>>>> c625e98880b704c0093ba7409f5a1602edcb2365
